data <- read.csv("household_power_consumption.txt", sep=";")
TempDate <- as.Date(data$Date,"%d/%m/%Y")
SubsetData <- subset(data, TempDate >= "2007-02-01" & TempDate <= "2007-02-02")
WD <- weekdays(as.Date(SubsetData$Date,'%d/%m/%Y'))
png("plot3.png", width = 480, height = 480)
DataPlot1 <- as.numeric(as.character(SubsetData$Sub_metering_1))
DataPlot2 <- as.numeric(as.character(SubsetData$Sub_metering_2))
DataPlot3 <- as.numeric(as.character(SubsetData$Sub_metering_3))
plot(1:2880, DataPlot1, xaxt ='n', type ="l", xlab="", col = 1:3,
     ylab = "Energy sub metering")
lines(DataPlot2, col = "red")
lines(DataPlot3, col = "blue")
axis(1, at = c(1,1441,2881), labels = c("Thu", "Fri", "Sat"))
legend("topright", lwd=2.0, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file = "plot3.png")
dev.off()
